### PR TITLE
Fixes #3: Fix linting issues, add ansible-lint and yamllint configuration.

### LINKED ISSUE #3: Lint Ansible playbook and tweak code style slightly (for readability)
**Version:**

N/A

**K3s arguments:**

N/A

**Describe the bug**

After applying the fix in https://github.com/rancher/k3s/pull/1730, to make the 'reboot on raspbian' task actually work (without a fatal error), I realized that this causes another problem: when the ARM servers reboot mid-playbook, the playbook fails. Even if only the `master` node fails, everything else will fail at the `Copy the K3s service file` task with the message:

    AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'

**To Reproduce**

Run the Ansible playbook on ARM servers.

**Expected behavior**

The playbook completes successfully, and reboots the ARM servers as required in the `Rebooting on Raspbian` task.

**Actual behavior**

```
TASK [raspbian : Rebooting on Raspbian] ********************************************************************************
Saturday 02 May 2020  11:36:06 -0500 (0:00:02.881)       0:00:38.813 ********** 
skipping: [worker-01]
skipping: [worker-02]
skipping: [worker-03]
skipping: [worker-04]
skipping: [worker-05]
skipping: [worker-06]
fatal: [turing-master]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to turing-master closed.", "unreachable": true}
```

Which, in turn, causes all the other hosts to fail:

```
TASK [k3s/node : Copy K3s service file] ********************************************************************************
Saturday 02 May 2020  11:36:14 -0500 (0:00:06.435)       0:00:46.844 ********** 
fatal: [worker-01]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"}
fatal: [worker-02]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"}
fatal: [worker-03]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"}
fatal: [worker-05]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"}
fatal: [worker-04]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"}
fatal: [worker-06]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"}
```

**Additional context / logs**

This was moved from the k3s repo issue https://github.com/rancher/k3s/issues/1724

### PR DESCRIPTION
**Pull request by geerlingguy**
Closes #3.﻿

### CODE REVIEW

**Comment by geerlingguy** [comment]
Note that this PR adds a GitHub action for linting that will run on any pull request or push to the master branch.

**Comment by geerlingguy** [comment]
Rebased.

**Comment by St0rmingBr4in** [comment]
The PR is good. However, we need to verify that Github action is suitable for this project. We will probably want to run the playbook in the CI to verify that it is working as expected in the future. I am not sure that Github action is the best choice. @itwars what do you think ?

**Comment by geerlingguy** [comment]
@St0rmingBr4in - I was considering also adding a separate workflow (or merging that into this lint.yml workflow and renaming the workflow) with a Molecule configuration that actually runs the playbook against a host, so it could also be used for local development and testing (in addition to CI), but I figured I'd do that separately, since the linting steps at least guarantee some amount of conformity/code structure.

**Comment by St0rmingBr4in** [comment]
Sure we will do that in another PR.
About CI choices lets wait @itwars input on GitHub action.
On the one hand GitHub action workflows can become ugly fast if we need to overcome some limitations. (Ability to share artifacts between workflows or dependence between workflows for instance)
On the other hand it's nicely integrated with GitHub and we could use some actions from the markeplace if needed.

**Comment by itwars** [comment]
LGTM

**Pull request merged**
